# source (maria db 만 가능)
# source, target (서로 같을 수 없음)
demo:
  datasource:
    source:
      url: jdbc:mariadb://192.168.137.73:3306/pmsportal
      username: lemonbada
      password: fpahsqkek
      driver-class-name: org.mariadb.jdbc.Driver

mybatis:
  configuration:
    multiple-result-sets-enabled: false
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: varchar
    default-fetch-size: 500

logging:
  file:
    path: batch-log
    max-size: 100MB
    max-history: 10
  level:
    root: error
    com.example.demo: debug